### PR TITLE
Some changes in WithHttpClientRequesters method

### PR DESCRIPTION
**Pull request by YehudahA**
1. I think it would be better to pass the HttClient himself. It allows more flexibility.
2. make overload names consistent.

### CODE REVIEW

**Comment by FlorianRappl** [comment]
The names are consistent for the future, as the provided methods will evolve to use a (not yet available) functionality for finding *all* registered requesters (the functionality is usually trivial to implement, but the PCL does not allow, e.g., scanning for libraries, so it has to be constructed differently). The method has nothing to do with the `HttpClient`.

AngleSharp.Io only provides the `HttpClient` because AngleSharp is a PCL and can't deliver it (and the `HttpClient` is a much more adequate solution than `WebRequest`). AngleSharp.Io will deliver more requesters in the future (e.g., `FtpRequester`, possibly the `DataRequester` will be part of AngleSharp.Io and not the core library).

Why do you need 1)? That kind of flexibility is already given (you can just create an instance of the requester, plus you can create an instance of the loader, plus ...). So no need to wrap it in another method. Right now the method gives you exactly what you want: convenience.

Finally, please look at `devel` (all PR have to be into `devel`). The most important changes are already there. Any comments?

**Comment by YehudahA** [comment]
I'm not sure I understood correctly: My rename is good or not?
```WithHttpClientRequester``` for ```HttpClientRequester``` and in the future you will have ```WithFrpRequester``` for ```FrpRequester```.
Perhaps you mean to use this method for **all** Requesters.

2) Inject ```HttpClient``` or his core handler is important for testing and mocking.
HttpClient gives me more flexability then HttpMessageHandler, for example I can set DefaultRequestHeaders.

[In fact, We are discussing about minor thing. As you said,this functionality is easy to implement]

**Comment by FlorianRappl** [comment]
Yes - this method is for **all** requesters. Therefore, the name has been chosen accordingly.

Yes, testing (and hence mocking) is very important, definitely. We agreed, this is possible and the provided method only exists for convenience. Nevertheless, I'll think about adding another overload with `HttpClient`. Yep, its just a minor thing.

**Comment by YehudahA** [comment]
So, you can reject and close this PR ...

**Comment by FlorianRappl** [comment]
You're welcome and thanks a lot for the discussion and the PR. :+1:

**Pull request closed without merging**
